version: '3'

volumes:
  db_volume: 

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_volume:/var/lib/mysql
    # why no port forwarding?

  app:
    # image: app
    build:
      context: ../app
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
    depends_on:
      - db
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"